# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  OGLRenderer_config = debug
  GLFW_config = debug
  glad_config = debug
  pugixml_config = debug
  fmt_config = debug
  imgui_config = debug
  assimp_config = debug

else ifeq ($(config),release)
  OGLRenderer_config = release
  GLFW_config = release
  glad_config = release
  pugixml_config = release
  fmt_config = release
  imgui_config = release
  assimp_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := OGLRenderer GLFW glad pugixml fmt imgui assimp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

OGLRenderer: GLFW glad pugixml fmt imgui assimp
ifneq (,$(OGLRenderer_config))
	@echo "==== Building OGLRenderer ($(OGLRenderer_config)) ===="
	@${MAKE} --no-print-directory -C OGLRenderer -f Makefile config=$(OGLRenderer_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C external/glfw -f Makefile config=$(GLFW_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C external/glad -f Makefile config=$(glad_config)
endif

pugixml:
ifneq (,$(pugixml_config))
	@echo "==== Building pugixml ($(pugixml_config)) ===="
	@${MAKE} --no-print-directory -C external/pugixml -f Makefile config=$(pugixml_config)
endif

fmt:
ifneq (,$(fmt_config))
	@echo "==== Building fmt ($(fmt_config)) ===="
	@${MAKE} --no-print-directory -C external/fmt -f Makefile config=$(fmt_config)
endif

imgui:
ifneq (,$(imgui_config))
	@echo "==== Building imgui ($(imgui_config)) ===="
	@${MAKE} --no-print-directory -C external/imgui -f Makefile config=$(imgui_config)
endif

assimp:
ifneq (,$(assimp_config))
	@echo "==== Building assimp ($(assimp_config)) ===="
	@${MAKE} --no-print-directory -C external/assimp -f Makefile config=$(assimp_config)
endif

clean:
	@${MAKE} --no-print-directory -C OGLRenderer -f Makefile clean
	@${MAKE} --no-print-directory -C external/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C external/glad -f Makefile clean
	@${MAKE} --no-print-directory -C external/pugixml -f Makefile clean
	@${MAKE} --no-print-directory -C external/fmt -f Makefile clean
	@${MAKE} --no-print-directory -C external/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C external/assimp -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   OGLRenderer"
	@echo "   GLFW"
	@echo "   glad"
	@echo "   pugixml"
	@echo "   fmt"
	@echo "   imgui"
	@echo "   assimp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"