# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  OGLRenderer_config = debug

else ifeq ($(config),release)
  OGLRenderer_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := OGLRenderer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

OGLRenderer:
ifneq (,$(OGLRenderer_config))
	@echo "==== Building OGLRenderer ($(OGLRenderer_config)) ===="
	@${MAKE} --no-print-directory -C OGLRenderer -f Makefile config=$(OGLRenderer_config)
endif

clean:
	@${MAKE} --no-print-directory -C OGLRenderer -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   OGLRenderer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"